### ISSUE TITLE
Admission Webhook charm rewrite using sidecar pattern

### ISSUE THREAD

**Issue by NohaIhab** [canonical/admission-webhook-operator#69]
# Admission Webhook charm rewrite using sidecar pattern
Work items are tracked in [Jira](https://warthogs.atlassian.net/browse/KF-706)

# Design
Design is specified in corresponding spec.

## Main design points summary:
- Use of sidecar pattern and Pebble layer.
- Porting of managing K8S resources from Pod Spec to Pebble framework.
- Pebble layer checks on admission-webhook service
- Handle upgrade and update status events
- Handle and test on remove event

# Testing
- Integration testing allows for verification of functionality.
- Created unit tests to cover charm functionality.

**Comment by i-chvets** [comment]
Completed.
